### ISSUE TITLE
Model selection practial/BC material

### ISSUE THREAD

**Issue by stefaniemuff** [opetchey/BIO144#82]
Practical for model selection: Should stress more the difference between explanatory and predictive models. In 2017 we had only exercises for automatic model selection, which might raise the impression that this is always "good". Similar comments for BC material.

**Comment by opetchey** [comment]
@stefaniemuff  can you make some suggestions about how to achieve this. What could / should be changed in the BC and IC material?

**Comment by stefaniemuff** [comment]
Idea 1: clearly stress that the abalone example is not an explanatory model, because the aim is to estimate (ie. predict) age. Therefore, automatic model selection is ok.
Idea 2: add another example with an explanatory model where students must select e.g. 2-4 variables from a larger set according to a priori knowledge
Idea 3: (maybe in place of idea 2) add an exercise with some questions that target at understanding. Maybe give a couple of problems and the students must decide in each case if it is an explanatory or a predictive model.

Does that sound useful?

**Comment by opetchey** [comment]
Thanks Steffi. I implemented idea 1 by adding text to the intro of the model selection example. It refers to your lecture content on this. Also I checked and see that the difference is highlighted at the start of the IC material.

I think we'd have to talk more about idea 2 and 3, as I don't really understand what these exercises would involve.

I think the two of might differ a bit here, for example in slide 21 of your lecture 7, I would write "we therefore strongly discourage the use of _only_ automated model selection procedures." Or even perhaps say there is a place for automated model selection in predictive model. Probably we should be a bit better aligned at least for the students!

**Comment by stefaniemuff** [comment]
Good point. By now the important distinction only comes after slides 34ff.

**Comment by opetchey** [comment]
Thinking about this again.

Idea 1. I have further clarified this in the relevant text. E.g. it is obvious this is not an explanatory model, as age cannot be caused by any of the explanatory variables -- its difficult (though perhaps not impossible) to think that size can be a cause of age.

Idea 2. There is an explanatory modelling exercise in the logistic regression example. Its about using species habitat requirements (Week 11, IC Practical Ptarmigans). They were already told here to choose variables to include based on a priori information, but it is now more explicit.

Idea 3. The students could be asked to look through all the problems they have addressed, and indicate / clarify whether they aim for explanation / understanding or prediction?
